name: Build and Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact_name: ROMMend-Windows.zip
            runtime: win-x64
          - os: ubuntu-latest
            artifact_name: ROMMend-Linux.AppImage
            runtime: linux-x64

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Get version
      id: version
      run: echo "version=$(date +'%Y.%m.%d').${{ github.run_number }}" >> $GITHUB_OUTPUT
        
    - name: Build and Publish
      shell: bash
      run: dotnet publish -c Release -r ${{ matrix.runtime }} -p:Version=${{ steps.version.outputs.version }} --self-contained true
      
    - name: Package (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        7z a ${{ matrix.artifact_name }} ./bin/Release/net8.0/${{ matrix.runtime }}/publish/*
      
    - name: Setup AppImage Tools (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2 imagemagick
        wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        chmod +x appimagetool
        sudo mv appimagetool /usr/local/bin/
      
    - name: Package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Create AppDir structure
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        
        # Copy application files
        cp -r ./bin/Release/net8.0/${{ matrix.runtime }}/publish/* AppDir/usr/bin/
        
        # Create desktop entry
        cat > AppDir/usr/share/applications/rommend.desktop << EOF
        [Desktop Entry]
        Name=ROMMend
        Exec=ROMMend
        Icon=rommend
        Type=Application
        Categories=Utility;
        Terminal=false
        EOF
        
        # Create AppRun script
        cat > AppDir/AppRun << EOF
        #!/bin/sh
        cd "\$(dirname "\$0")/usr/bin"
        exec ./ROMMend "\$@"
        EOF
        chmod +x AppDir/AppRun
        
        # Create icon
        convert -size 256x256 xc:transparent -fill "#2a82da" -draw "circle 128,128 128,64" AppDir/usr/share/icons/hicolor/256x256/apps/rommend.png
        
        # Set executable permissions
        chmod +x AppDir/usr/bin/ROMMend
        
        # Create AppImage
        appimagetool AppDir ${{ matrix.artifact_name }}
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        files: ${{ matrix.artifact_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
